```python
# app/schemas/__init__.py

from typing import List, Optional
from pydantic import BaseModel, HttpUrl, Field


class TranscriptRequest(BaseModel):
    """
    Request schema for submitting a YouTube video URL to extract and summarize transcript.
    """
    url: HttpUrl = Field(
        ...,
        description="The full YouTube video URL."
    )


class TranscriptResponse(BaseModel):
    """
    Response schema containing the original transcript, summary, and estimated categories.
    """
    transcript: str = Field(
        ...,
        description="The full extracted transcript from the YouTube video."
    )
    summary: str = Field(
        ...,
        description="A concise summary of the transcript generated by GPT-4."
    )
    categories: List[str] = Field(
        ...,
        description="Estimated video categories based on the transcript content."
    )


class ErrorResponse(BaseModel):
    """
    Standard error response schema.
    """
    detail: str = Field(
        ...,
        description="A human-readable error message."
    )
    code: Optional[int] = Field(
        None,
        description="Optional error code."
    )
```